# Global Variables

title: More Tongues Than Teeth
description: Brooklyn-based rock band.
keywords:
  - band
  - music
  - rock
  - indie rock
  - Brooklyn
baseurl: ""
url: "http://www.moretongues.com"
google_analytics: "UA-101639062-1"
contact:
  facebook: "https://www.facebook.com/MoreTonguesThanTeeth/"
  instagram: "https://www.instagram.com/moretonguesthanteeth"
  twitter: "@moretongues"
  youtube: "https://www.youtube.com/channel/UCXUKrkDX88zx1bL4Xu8qZYw"
  email: "moretonguesthanteeth@gmail.com"
permalink: /:title/

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "node*"
  - "package*.json"
  - "gulpfile.js"
