# Global Variables

title: More Tongues Than Teeth
description: A Mouthful of Fun
baseurl: "/mt3"
url: "https://dawaltconley.github.io"
contact:
  email: "moretonguesthanteeth@gmail.com"
  phone:
  twitter: "@moretongues"
  google-plus:
  facebook: "https://www.facebook.com/MoreTonguesThanTeeth/"
  youtube: "https://www.youtube.com/channel/UCXUKrkDX88zx1bL4Xu8qZYw"
  linkedin:
  vimeo:
  instagram: "https://www.instagram.com/moretonguesthanteeth"
permalink: /:title/

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
