# Global Variables

title: More Tongues Than Teeth
description: A Mouthful of Fun
baseurl: ""
url: "https://dawaltconley.github.io"
google_analytics: "UA-101639062-1"
contact:
  facebook: "https://www.facebook.com/MoreTonguesThanTeeth/"
  instagram: "https://www.instagram.com/moretonguesthanteeth"
  twitter: "@moretongues"
  youtube: "https://www.youtube.com/channel/UCXUKrkDX88zx1bL4Xu8qZYw"
  email: "moretonguesthanteeth@gmail.com"
permalink: /:title/

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
