# Global Variables

title: More Tongues Than Teeth
description: A Mouthful of Fun
baseurl: "/mt3"
url: "https://dawaltconley.github.io"
permalink: /:title/

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
