# Global Variables

title: NYC-DSA Anti-War Working Group
keywords: # a YAML list. optional; only used by some older search engines.
baseurl: # for hosting at a subdomain
url: https://antiwar.netlify.com/ # full url of main site
og_image: /assets/logos/og-banner.jpg # default og image used for entire site; can be overridden if specified in page or collection frontmatter
google_analytics: # tracking number
permalink: /:title/ # default permalink structure for pages
copyright:
  date: 2019-08-20T00:02:00-4:00 # date the site was created
  owner: Dylan Awalt-Conley # owner of the site

timezone: America/New_York # used for liquid-generated datetimes
auto_scroll: false # enables smooth scrolling for all same-page links using zenscroll
native_scroll: false # enables smooth scrolling by the scroll-behavior property, for all browsers that support it
bg_testing: false # turn on to enable the bg-testing.html include
emptyArray: [] # variable for easy array creation
logo:
  og:
    basic: /assets/logos/dsa_anti-war_logo_transparent_basic.png
    black_text: /assets/logos/dsa_anti-war_logo_transparent.png
    white_text: /assets/logos/dsa_anti-war_logo_transparent_white_text.png
  white:
    basic: /assets/logos/dsa_anti-war_white_transparent_basic.png
    text: /assets/logos/dsa_anti-war_white_transparent.png

# Collections

collections:
  campaigns:
    output: true

defaults:
  - scope:
      path: _campaigns
    values:
      layout: campaign
      permalink: /:path/
      sub_campaign: false
  - scope:
      path: _campaigns/*/*
    values:
      sub_campaign: true

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "package*.json"
  - "node_modules"
  - "gulpfile.js"
  - "assets/test"

# Prose

prose:
  ignore:
    - "*.html"
    - "*.svg"
    - "*.xml"
    - "*.liquid"
    - "*.js"
    - "*.json"
    - "*.jsonp"
    - "*.rb"
    - "*.sh"
    - "_layouts"
    - "_sass"
    - "_site"
    - "css"
    - "js"
    - "assets"
    - "_data/icon-types.yml"
    - "_includes/lorem-ipsum.md"
    - "_config*.yml"
    - "README.md"
    - ".*rc"
    - ".ruby-version"
    - ".nvmrc"
    - ".gitignore"
    - "Gemfile*"
