---
---

backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
collections:
  - label: Campaigns
    label_singular: Campaign
    name: campaigns
    folder: _campaigns
    extension: md
    create: true
    slug: {% raw %}"{{ short_title }}"{% endraw %}
    fields:
      - label: Title
        name: title
        widget: string
      - label: Short Title
        name: short_title
        widget: string
      - label: Body
        name: body
        widget: markdown
{% for c in site.campaigns %}
  - label: {{ c.short_title }}
    name: {{ c.short_title | slugify }}
    folder: {{ c.slug }}
    extension: md
    create: true
    slug: {% raw %}"{{ short_title }}"{% endraw %}
    fields:
      - label: Title
        name: title
        widget: string
      - label: Short Title
        name: short_title
        widget: string
      - label: Body
        name: body
        widget: markdown
      - lable: Layout
        name: layout
        widget: hidden
        default: page
{% endfor %}
