---
---

# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
site_url: {{ site.url }}
{% if site.logo %}
logo_url: {{ site.logo.og.basic }}
{% endif %}
collections:
  - label: Campaigns
    label_singular: Campaign
    name: campaigns
    folder: _campaigns
    extension: md
    format: yaml-frontmatter
    create: true
    identifier_field: short_title
    slug: {% raw %}"{{slug}}"{% endraw %}
    preview_page: {% raw %}"{{slug}}"{% endraw %}
    description: >
      Overviews of the general campaigns adopted
      by the working group. Each campaign page also
      features links to related goals and demands,
      which live in the campaign's directory. Creating
      a new campaign will also generate a new directory.
    fields:
      - label: Title
        name: title
        widget: string
        default: New Campaign
        hint: Full title, used at the top of the page.
      - label: Short Title
        name: short_title
        widget: string
        hint: >
          Used for the page url, as well as
          some menus and references to the page.
          Should be as short as possible!
      - label: Body
        name: body
        widget: markdown
        default: Information about the new campaign.
{% for c in site.campaigns %}{% unless c.sub_campaign %}
  - label: {{ c.short_title }}
    name: {{ c.short_title | slugify }}
    folder: _campaigns/{{ c.slug }}
    extension: md
    format: yaml-frontmatter
    create: true
    identifier_field: short_title
    slug: {% raw %}"{{slug}}"{% endraw %}
    preview_page: "{{ c.slug }}/{% raw %}{{slug}}{% endraw %}"
    description: >
      This collection is for pages describing the
      various specific goals and demands of the
      {{ c.short_title }} campaign. These will appear
      on their own pages, linked to from the main
      {{ c.short_title }} campaign page.
    fields:
      - label: Title
        name: title
        widget: string
        default: New {{ c.short_title }} Campaign
        hint: Full title, used at the top of the page.
      - label: Short Title
        name: short_title
        widget: string
        hint: >
          Used for the page url, as well as
          some menus and references to the page.
          Should be as short as possible!
      - label: Body
        name: body
        widget: markdown
        default: Information about the new campaign.
      - label: Campaign Page Blurb
        name: blurb
        widget: markdown
        required: false
        hint: >
          Short description, used on the {{ c.short_title }} campaign page.
          If blank, defaults to the first paragraph of the body.
      - lable: Layout
        name: layout
        widget: hidden
        default: page
{% endunless %}{% endfor %}
  - label: Data
    name: data
    editor:
      preview: false
    description: >
      This is where you will be able to update different
      types of data, which are used throughout the site.
    files:
      - label: Site Data
        name: site
        file: _config.yml
        fields:
          - label: Site title
            name: title
            widget: string
          - label: Site description
            name: description
            widget: string
          - label: Copyright
            name: copyright
            widget: object
            fields:
              - label: Copyright date
                name: date
                widget: datetime
                format: "YYYY-MM-DDTHH:mm:ssZ"
                hint: >
                  Usually the date the site was created,
                  unless otherwise renewed.
              - label: Site owner
                name: owner
                widget: string
          - label: Site image
            name: og_image
            required: false
            widget: image
            allow_multiple: false
          - label: Google Analytics
            name: google_analytics
            required: false
            widget: string
            hint: >
              Enter your tracking number to turn on analytics
              for the site.
      - label: Contact info
        name: contact
        file: _data/contact.yml
        fields: {% for c in site.data.icon-types %}
          - label: {{ c.label }}
            name: {{ c.type }}
            required: false
            widget: string {% endfor %}
