---
---

# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
site_url: {{ site.url }}
{% if site.logo %}
logo_url: {{ site.logo }}
{% endif %}
collections:
  - label: Posts
    label_singular: Post
    name: posts
    folder: _posts
    extension: md
    create: true
    slug: {% raw %}"{{ year }}-{{ month }}-{{ day }}-{{ title }}"{% endraw %}
    preview_page: {% raw %}"{{ slug }}"{% endraw %}
    description: >
      The basic type of content.
    fields:
      - label: Title
        name: title
        widget: string
        default: New Post
        hint: Full title, used at the top of the page.
      - label: Publish Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:MM:SS"
      - label: Body
        name: body
        widget: markdown
        default: New day, new post!
  - label: Data
    name: data
    description: >
      This is where you will be able to update different
      types of data, which are used throughout the site.
    files:
      - label: Contact Info
        name: contact
        file: _data/contact.yml
        fields: {% for c in site.data.contact %}
          - label: {{ c[0] | capitalize }}
            name: {{ c[0] }}
            required: false
            widget: string {% endfor %}
