backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
collections:
  - label: Campaigns
    name: campaigns
    folder: _campaigns
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
